language: ruby
rvm:
- 2.0.0-p481
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: tfFgy2pNm3npyN6TkmZznkzJrjca8ADi54SOfEF54YSCIeqLIYJmS+th5R+gHEBkGy77vgOoCnv2X8a0xuwO8A8rqxHieMglo1Ko1AOHuRM1JNX8TpGmcYNaw15dWfjE7TH5yRJgB98OVecH+Gsnip3xAEVlErHB1hncOAnBCkU=
  app: feedmeapp
  on:
    repo: toannguyenle/feedmeapp
  run:
  #remember that migrations you run locally must run in the release environment
    - "rake db:migrate"
    - restart